---

dist: xenial

language: python
python: 
  - '3.7'

before_install:
    - sudo apt-get update -qq

install:
    # Install requirements
    - pip install -r requirements.txt

script:
    - chmod +x run_tests.sh
    - ./run_tests.sh
